#!/usr/bin/env python

import argparse

from utils.html2epub import convert

parser = argparse.ArgumentParser(description='Extract html files from epub file')

parser.add_argument('Path',
                    metavar='path',
                    type=str,
                    help='the path to epub file')

args = parser.parse_args()
convert(args.Path)
